<a href="https://colab.research.google.com/github/Prajwalkoladur/Prajwal-Koladur/blob/main/Py_asign_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array'''
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])


print(sales_data.ndim)
print(sales_data.shape)
print(sales_data.size)
print(sales_data.dtype)
print(sales_data.itemsize)


2
(5, 6)
30
int64
8


In [ ]:
'''Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations'''

print(len(stores))
print(len(categories))
print(len(stores)*len(categories))


5
6
30


In [ ]:
'''Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.'''

float32 = sales_data.astype('float32')
float64= sales_data.astype('float64')

print(f"Sales data as float32:\n{float32}")
print(f"Sales data as float64:\n{float64}")

print(float32.nbytes)
print(float64.nbytes)

Sales data as float32:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
Sales data as float64:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
120
240


In [ ]:
'''Part 3: Indexing and Data Extraction
Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.'''
bengaluru =sales_data[0]
print(bengaluru)


[850000 420000 310000 275000 190000 225000]


In [ ]:
'''Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories'''
mumbai = cost_data[3]
sum = np.sum(mumbai)
print(sum)

2065000


In [ ]:
'''Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data'''
electronics = sales_data[0:6,0]
print(electronics)

[ 850000  780000  920000 1050000  690000]


In [ ]:
'''Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.'''
clothing = cost_data[0:6,2]
print(clothing)

[220000 210000 245000 265000 205000]


In [ ]:
'''Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit'''
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
furniture_sales = sales_data[1]
furniture_cost = cost_data[1]
furniture_profit = furniture_sales - furniture_cost
print(furniture_sales)
print(furniture_cost)
print(furniture_profit)



[780000 460000 295000 310000 210000 240000]
[590000 350000 210000 225000 140000 170000]
[190000 110000  85000  85000  70000  70000]


In [ ]:
'''Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.'''
chennai = sales_data[2]
chennai = chennai[1:4]
print(chennai)

[390000 340000 260000]


In [ ]:
'''Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.'''
selected_stores = sales_data[[0,2,4]]
categories =[0,2,4]
print(selected_stores[:,categories])


[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [ ]:
'''Part 4: Sales Aggregation
Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories'''
total_sales = np.sum(sales_data)
print(total_sales)

11675000


In [ ]:
'''Question 12: Store-Wise Sales
Calculate total sales revenue for each store.
Display the result together with the store names.
Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales'''
total_sales_Bengaluru = np.sum(sales_data[0])
tatal_sales_Hyderabad = np.sum(sales_data[1])
total_sales_Chennai = np.sum(sales_data[2])
total_sales_Mumbai = np.sum(sales_data[3])
total_sales_Pune= np.sum(sales_data[4])
print(f"bengaluru total sales :{total_sales_Bengaluru}")
print(f"hyderabad total sales :{tatal_sales_Hyderabad }")
print(f"chennai total sales   :{total_sales_Chennai}")
print(f"mumbai total sales    :{total_sales_Mumbai}")
print(f"mumbai  total sales   :{total_sales_Pune}")

bengaluru total sales :2270000
hyderabad total sales :2295000
chennai total sales   :2310000
mumbai total sales    :2820000
mumbai  total sales   :1980000


In [ ]:
'''Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.'''
product_category = np.sum(cost_data,axis = 0)
product_category =np.split(product_category,6)
print(f"electronics total sales:{product_category[0]}")
print(f"groceries total sales :{product_category[1]}")
print(f"clothing total sales  :{product_category[2]}")
print(f"furniture total sales :{product_category[3]}")

electronics total sales:[3250000]
groceries total sales :[1660000]
clothing total sales  :[1145000]
furniture total sales :[1045000]


In [ ]:
'''Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.'''

average_sales_per_store = np.mean(sales_data, axis=1)
for i, store_name in enumerate(stores):
    print(f"{store_name}: {average_sales_per_store[i]:.2f}")

Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00


In [ ]:
'''Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.'''
average_sales_per_category = np.mean(sales_data, axis=1)
for i, category_name in enumerate(categories):
    print(f"{category_name}: {average_sales_per_category[i]:.2f}")

0: 378333.33
2: 382500.00
4: 385000.00


In [ ]:
'''Question 16: Highest-Selling Store
Identify:
Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().'''
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

highest_selling_store = np.argmax(np.sum(sales_data, axis=1))
highest_selling_store_name = stores[highest_selling_store]
highest_selling_store_total_sales = np.sum(sales_data[highest_selling_store])
print(f"Index of the store with the highest total sales: {highest_selling_store}")
print(f"Name of the store: {highest_selling_store_name}")
print(f"Total sales generated by that store: {highest_selling_store_total_sales}")

Index of the store with the highest total sales: 3
Name of the store: Mumbai
Total sales generated by that store: 2820000


In [ ]:
'''Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().'''
import numpy as np
lowest_selling_store = np.argmin(np.sum(sales_data, axis=1))
lowest_selling_store_name = stores[lowest_selling_store]
lowest_selling_store_total_sales = np.sum(sales_data[lowest_selling_store])
print(f"Index of the store with the lowest total sales: {lowest_selling_store}")
print(f"Name of the store: {lowest_selling_store_name}")
print(f"Total sales generated by that store: {lowest_selling_store_total_sales}")

Index of the store with the lowest total sales: 4
Name of the store: Pune
Total sales generated by that store: 1980000


In [ ]:
'''Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.'''
import numpy as np
highest_selling_category = np.argmax(np.sum(sales_data, axis=0))
highest_selling_category_name = categories[highest_selling_category]
highest_selling_category_total_sales = np.sum(sales_data[:, highest_selling_category])
print(f"Index of the category with the highest total sales: {highest_selling_category}")
print(f"Name of the category: {highest_selling_category_name}")
print(f"Total sales generated by that category: {highest_selling_category_total_sales}")

Index of the category with the highest total sales: 0
Name of the category: Electronics
Total sales generated by that category: 4290000


In [ ]:
'''Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.'''
import numpy as np
lowest_selling_category = np.argmin(np.sum(sales_data, axis=0))
lowest_selling_category_name = categories[lowest_selling_category]
lowest_selling_category_total_sales = np.sum(sales_data[:, lowest_selling_category])
print(f"Index of the category with the lowest total sales: {lowest_selling_category}")
print(f"Name of the category: {lowest_selling_category_name}")
print(f"Total sales generated by that category: {lowest_selling_category_total_sales}")

Index of the category with the lowest total sales: 4
Name of the category: Beauty
Total sales generated by that category: 1010000


In [ ]:
'''Part 5: Cost Analysis
Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.'''
import numpy as np
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
total_cost = np.sum(cost_data)
print(total_cost)

8600000


In [ ]:
'''Question 21: Store-Wise Cost
Calculate the total cost incurred by each store.'''
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"])
store_wise_costs = np.sum(cost_data, axis=1)
for i, store_name in enumerate(stores):
    print(f"Total cost for {store_name}: {store_wise_costs[i]}")

Total cost for Bengaluru: 1665000
Total cost for Hyderabad: 1685000
Total cost for Chennai: 1710000
Total cost for Mumbai: 2065000
Total cost for Pune: 1475000


In [ ]:
'''Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores'''
import numpy as np
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
category_wise_costs = np.sum(cost_data, axis=0)
for i, category_name in enumerate(categories):
    print(f"Total cost for {category_name}: {category_wise_costs[i]}")

Total cost for Electronics: 3250000
Total cost for Groceries: 1660000
Total cost for Clothing: 1145000
Total cost for Furniture: 1045000
Total cost for Beauty: 665000
Total cost for Sports: 835000


In [ ]:
'''Question 23: Most Expensive Store
Identify the store with the highest total operating cost.'''
import numpy as np
most_expensive_store = np.argmax(np.sum(cost_data, axis=1))
most_expensive_store_name = stores[most_expensive_store]
most_expensive_store_total_cost = np.sum(cost_data[most_expensive_store])
print(f"store with the highest total operating cost: {most_expensive_store}")
print(f"Name of the store: {most_expensive_store_name}")
print(f"Total operating cost for that store: {most_expensive_store_total_cost}")

store with the highest total operating cost: 3
Name of the store: Mumbai
Total operating cost for that store: 2065000


In [ ]:
'''Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.'''
import numpy as np
lowest_cost_store = np.argmin(np.sum(cost_data, axis=1))
lowest_cost_store_name = stores[lowest_cost_store]
lowest_cost_store_total_cost = np.sum(cost_data[lowest_cost_store])
print(f"store with the lowest total operating cost: {lowest_cost_store}")
print(f"Name of the store: {lowest_cost_store_name}")
print(f"Total operating cost for that store: {lowest_cost_store_total_cost}")

store with the lowest total operating cost: 4
Name of the store: Pune
Total operating cost for that store: 1475000


In [ ]:
'''Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.'''

import numpy as np
most_expensive_category = np.argmax(np.sum(cost_data, axis=0))
most_expensive_category_name = categories[most_expensive_category]
most_expensive_category_total_cost = np.sum(cost_data[:, most_expensive_category])
print(f"product category with the highest total operating cost: {most_expensive_category}")
print(f"Name of the category: {most_expensive_category_name}")
print(f"Total operating cost for that category: {most_expensive_category_total_cost}")

product category with the highest total operating cost: 0
Name of the category: Electronics
Total operating cost for that category: 3250000


In [112]:
'''Part 6: Profit Analysis Using Two Arrays
Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:
profit_data = sales_data - cost_data
Display the complete profit matrix.'''

import numpy as np

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
profit_data = sales_data - cost_data
print("Profit matrix: ", profit_data)

Profit matrix:  [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [113]:
'''Question 27: Store-Wise Profit
Calculate the total profit generated by each store.'''
import numpy as np
stores = np.array(["Bengaluru","Hyderabad","Chennai","Mumbai","pune"])
store_wise_profit = np.sum(profit_data, axis=1)
for i, store_name in enumerate(stores):
    print(f"Total profit for {store_name}: {store_wise_profit[i]}")

Total profit for Bengaluru: 605000
Total profit for Hyderabad: 610000
Total profit for Chennai: 600000
Total profit for Mumbai: 755000
Total profit for pune: 505000


In [ ]:
'''Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.'''
import numpy as np
categories = np.array(["Electronics","Groceries","Clothing","Furniture","Beauty","Sports"])
category_wise_profit = np.sum(profit_data, axis=0)
for i, category_name in enumerate(categories):
    print(f"Total profit for {category_name}: {category_wise_profit[i]}")

Total profit for Electronics: 1040000
Total profit for Groceries: 525000
Total profit for Clothing: 455000
Total profit for Furniture: 370000
Total profit for Beauty: 345000
Total profit for Sports: 340000


In [115]:
'''Question 29: Most Profitable Store
Identify the store that generated the highest total profit.
Display:
Store name
Total sales
Total cost
Total profit'''

import numpy as np
most_profitable_store = np.argmax(store_wise_profit)
print("Most profitable store: ", stores[most_profitable_store])
print("Total sales: ", np.sum(sales_data[most_profitable_store]))
print("Total cost: ", np.sum(cost_data[most_profitable_store]))
print("Total profit: ", store_wise_profit[most_profitable_store])

Most profitable store:  Mumbai
Total sales:  2820000
Total cost:  2065000
Total profit:  755000


In [117]:
'''Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.'''
import numpy as np
least_profitable_store = np.argmin(store_wise_profit)
print("Least profitable store: ", stores[least_profitable_store])

Least profitable store:  pune


In [119]:
'''Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.'''
import numpy as np
category_wise_profit = np.sum(profit_data, axis=0)
most_profitable_category = np.argmax(category_wise_profit)
print("Most Profitable Category: ", categories[most_profitable_category])

Most Profitable Category:  Electronics


In [120]:
'''Question 32: Least Profitable Category
Find the category with the lowest total profit.'''
import numpy as np
least_profitable_category = np.argmin(category_wise_profit)
print("Least Profitable Category: ", categories[least_profitable_category])

Least Profitable Category:  Sports


In [121]:
'''Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().'''
import numpy as np
maximum_individual_profit = np.unravel_index(np.argmax(profit_data), profit_data.shape)
print("Maximum Individual Profit: ", profit_data[maximum_individual_profit])

Maximum Individual Profit:  260000


In [122]:
'''Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.'''
import numpy as np
minimum_individual_profit = np.unravel_index(np.argmin(profit_data), profit_data.shape)
print("Minimum Individual Profit: ", profit_data[minimum_individual_profit])

Minimum Individual Profit:  55000


In [123]:
'''Part 7: Profit Margin Analysis
Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.
Use:
profit_margin = (profit_data / sales_data) * 100
Round the result to two decimal places.'''
import numpy as np
profit_margin = (profit_data / sales_data) * 100
print(profit_margin)

[[24.70588235 25.         29.03225806 25.45454545 34.21052632 28.88888889]
 [24.35897436 23.91304348 28.81355932 27.41935484 33.33333333 29.16666667]
 [23.91304348 24.35897436 27.94117647 25.         35.13513514 27.90697674]
 [24.76190476 23.52941176 29.33333333 27.53623188 34.         29.31034483]
 [23.1884058  23.45679012 26.78571429 24.44444444 34.28571429 29.26829268]]


In [124]:
'''Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

Store Profit Margin =Total Store Profit / Total Store Sales × 100'''
import numpy as np
store_wise_profit_margin = np.sum(profit_data, axis=1)
store_wise_total_sales = np.sum(sales_data, axis=1)
store_wise_profit_margin_percentage = (store_wise_profit_margin / store_wise_total_sales) * 100
print(store_wise_profit_margin_percentage)

[26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]


In [ ]:
'''Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.'''
import numpy as np
category_wise_profit_margin = np.sum(profit_data, axis=0)
category_wise_total_sales = np.sum(sales_data, axis=0)
category_wise_profit_margin_percentage = (category_wise_profit_margin / category_wise_total_sales) * 100
print(category_wise_profit_margin_percentage)

[24.24242424 24.02745995 28.4375     26.14840989 34.15841584 28.93617021]


In [125]:
'''Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin'''

import numpy as np
best_store_by_profit_margin = np.argmax(store_wise_profit_margin)
print("Best Store by Profit Margin: ", stores[best_store_by_profit_margin])

Best Store by Profit Margin:  Mumbai


In [ ]:
'''Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.'''
import numpy as np
category_wise_profit_margin = np.sum(profit_data, axis=0)
category_wise_total_sales = np.sum(sales_data, axis=0)
category_wise_profit_margin_percentage = (category_wise_profit_margin / category_wise_total_sales) *100
best_category_index = np.argmax(category_wise_profit_margin_percentage)
best_category_name = categories[best_category_index]
print(f"Best category by profit margin: {best_category_name}")
print(f"higest overall profit margin: {category_wise_profit_margin_percentage[best_category_index]}")

Best category by profit margin: Beauty
higest overall profit margin: 34.15841584158416


In [126]:
'''Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing'''

import numpy as np
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
low_margin_transactions = profit_margin < 22
print("Low Margin Transactions:")
print(low_margin_transactions)
rows, cols = np.where(low_margin_transactions)
print("\nStore:", stores[rows])
print("Category:", categories[cols])
print("Sales:", sales_data[rows, cols])
print("Cost:", cost_data[rows, cols])
print("Profit:", profit_data[rows, cols])
print("Profit Margin:", profit_margin[rows, cols])


Low Margin Transactions:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]

Store: []
Category: []
Sales: []
Cost: []
Profit: []
Profit Margin: []


In [ ]:
'''Part 8: Boolean Filtering
Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.'''
import numpy as np
high_sales_values = sales_data[sales_data > 500000]
print(high_sales_values)

[ 850000  780000  920000 1050000  510000  690000]


In [ ]:
'''Question 42: Low Sales Values
Find all sales values below ₹2,00,000'''
import numpy as np
low_sales_values = sales_data[sales_data < 200000]
print(low_sales_values)

[190000 185000 175000]


In [ ]:
'''Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.'''
import numpy as np
high_profit_values = profit_data[profit_data > 150000]
print(high_profit_values)

[210000 190000 220000 260000 160000]


In [ ]:
'''Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().'''
import numpy as np
sales_values_between_250000_500000 = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]
print(sales_values_between_250000_500000)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [ ]:
'''Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations'''
import numpy as np
premium_combinations = (sales_data > 500000) & (profit_data > 150000)
print(premium_combinations)

[[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]]


In [ ]:
'''Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.'''
import numpy as np
sales_below_250000 = sales_data < 250000
profit_margin_below_25 = (profit_data / sales_data) * 100 < 25
underperforming_combinations = np.logical_and(sales_below_250000, profit_margin_below_25)
print(underperforming_combinations)


[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [ ]:
'''Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().'''
import numpy as np
sales_classification = np.where(sales_data >= 500000, "High", np.where(sales_data >= 250000, "Medium", "Low"))
print(sales_classification)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


In [ ]:
'''Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting'''
import numpy as np
sales_targets = np.array([800000,450000,320000,300000,200000,230000])
store_category_sales_comparison = sales_data / sales_targets
print(store_category_sales_comparison)

[[1.0625     0.93333333 0.96875    0.91666667 0.95       0.97826087]
 [0.975      1.02222222 0.921875   1.03333333 1.05       1.04347826]
 [1.15       0.86666667 1.0625     0.86666667 0.925      0.93478261]
 [1.3125     1.13333333 1.171875   1.15       1.25       1.26086957]
 [0.8625     0.9        0.875      0.75       0.875      0.89130435]]


In [ ]:
'''Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target'''
import numpy as np
target_achievement_matrix = sales_data >= sales_targets
print(target_achievement_matrix)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [ ]:
'''Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target'''
import numpy as np
target_achievement_count = np.sum(sales_data >= sales_targets, axis=1)
print(target_achievement_count)

[1 4 2 6 0]


In [ ]:
'''Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.'''
import numpy as np
best_target_performing_store = np.argmax(np.sum(sales_data >= sales_targets, axis=1))
print(f"Best target-performing store: {best_target_performing_store}")

Best target-performing store: 3


In [ ]:
'''Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.'''
import numpy as np
target_achievement_by_category = np.sum(sales_data >= sales_targets, axis=0)
print(target_achievement_by_category)


[3 2 2 2 2 2]


In [ ]:
'''Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales'''
import numpy as np
sales_target_variance = sales_data - sales_targets
print(sales_target_variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [ ]:
'''Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100'''
import numpy as np
percentage_variance_from_target = ((sales_data - sales_targets) / sales_targets) * 100
print(percentage_variance_from_target)

[[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


In [97]:
'''
Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.'''

import numpy as np
sales_targets = np.array([800000,450000,320000,300000,200000,230000])
electronics_target = sales_targets[0]
stores_missing_electronics_target = np.where(sales_data[:, 0] < electronics_target)[0]
print("Stores Missing Electronics Target: ", stores_missing_electronics_target)

Stores Missing Electronics Target:  [1 4]


In [ ]:
'''Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().'''
import numpy as np
stores_achieving_all_targets = np.all(sales_data >= sales_targets, axis=1)
print(stores_achieving_all_targets)

[False False False  True False]


In [ ]:
'''
Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().'''
import numpy as np
stores_achieving_at_least_one_target = np.any(sales_data >= sales_targets, axis=1)
print(stores_achieving_at_least_one_target)

[ True  True  True  True False]


In [110]:
'''Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.'''

import numpy as np
discount_rates = np.array([0.10,0.05,0.15,0.12,0.08,0.10,])
print("Discount Rates: ", discount_rates)


Discount Rates:  [0.1  0.05 0.15 0.12 0.08 0.1 ]


In [99]:
'''Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.'''

import numpy as np
discount_amount = sales_data * discount_rates
net_sales = sales_data - discount_amount
print("Net Sales: ", net_sales)

Net Sales:  [[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [100]:
'''Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.'''
import numpy as np
profit = net_sales - cost_data
print("Profit: ", profit)


Profit:  [[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [101]:
'''Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.'''

import numpy as np
profit_margin = (profit / net_sales) * 100
print("Profit Margin: ", profit_margin)

Profit Margin:  [[16.33986928 21.05263158 16.5085389  15.2892562  28.48970252 20.98765432]
 [15.95441595 19.90846682 16.25124626 17.52199413 27.53623188 21.2962963 ]
 [15.4589372  20.37786775 15.22491349 14.77272727 29.4947121  19.89664083]
 [16.4021164  19.50464396 16.8627451  17.65480896 28.26086957 21.4559387 ]
 [14.65378422 19.42820013 13.86554622 14.14141414 28.57142857 21.40921409]]


In [102]:
'''Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.'''

import numpy as np
loss_making_transactions = profit < 0
print("Loss-Making Transactions: ", loss_making_transactions)
affected_stores = np.where(loss_making_transactions)[0]
affected_categories_names = np.where(loss_making_transactions)[1]
print("Affected Stores: ", affected_stores)
print("Affected Categories: ", affected_categories_names)



Loss-Making Transactions:  [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
Affected Stores:  []
Affected Categories:  []


In [103]:
'''Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.'''

import numpy as np
discount_impact = np.sum(sales_data * discount_rates)
print("Discount Impact: ", discount_impact)


Discount Impact:  1146350.0


In [104]:
'''Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.'''
import numpy as np
discount_impact = np.sum(sales_data * discount_rates, axis=1)
store_most_affected_by_discounts = np.argmax(discount_impact)
print("Store Most Affected by Discounts: ", stores[store_most_affected_by_discounts])


Store Most Affected by Discounts:  Mumbai


In [105]:
'''Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

tax_rates = np.array([0.18,0.05,0.12,0.18,0.18,0.12])
Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.'''
import numpy as np
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
tax_rates = np.array([0.18,0.05,0.12,0.18,0.18,0.12])
tax_collection = sales_data * tax_rates
print(tax_collection)


[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [106]:
'''Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.'''

import numpy as np
sales_including_tax = sales_data + tax_collection
customer_billing_value = sales_including_tax
print("Customer Billing Value After Adding Tax: ", customer_billing_value)


Customer Billing Value After Adding Tax:  [[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [107]:
'''Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.'''

import numpy as np
store_wise_tax_collection = np.sum(tax_collection, axis=1)
print("Store-Wise Tax Collection: ", store_wise_tax_collection)

Store-Wise Tax Collection:  [321900. 321200. 331800. 401400. 274650.]


In [108]:
'''Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.'''
import numpy as np
category_wise_tax_collection = np.sum(tax_collection, axis=0)
print("Category-Wise Tax Collection: ", category_wise_tax_collection)


Category-Wise Tax Collection:  [772200. 109250. 192000. 254700. 181800. 141000.]


In [109]:
'''Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.'''
import numpy as np
highest_tax_contributing_store = np.argmax(store_wise_tax_collection)
print("Highest Tax-Contributing Store: ", stores[highest_tax_contributing_store])

Highest Tax-Contributing Store:  Mumbai


In [93]:
'''Part 12: Array Modification
Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.'''

import numpy as np
pune_electronics_sales = sales_data[1, 0]
updated_pune_electronics_sales = np.copy(sales_data)
updated_pune_electronics_sales[1, 0] = 740000
print("Original Sales Data: ", sales_data)
print("Updated Pune Electronics Sales: ", updated_pune_electronics_sales)

Original Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Updated Pune Electronics Sales:  [[ 850000  420000  310000  275000  190000  225000]
 [ 740000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [38]:
'''Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.'''

import numpy as np
reduced_cost = cost_data * 0.92
print("Reduced Cost: ", reduced_cost)

Reduced Cost:  [[588800. 289800. 202400. 188600. 115000. 147200.]
 [542800. 322000. 193200. 207000. 128800. 156400.]
 [644000. 271400. 225400. 179400. 110400. 142600.]
 [726800. 358800. 243800. 230000. 151800. 188600.]
 [487600. 285200. 188600. 156400. 105800. 133400.]]


In [39]:
'''Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.'''

import numpy as np
Furniture_cost_increase = cost_data * 1.12
print("Furniture Cost Increase: ", Furniture_cost_increase)

Furniture Cost Increase:  [[716800. 352800. 246400. 229600. 140000. 179200.]
 [660800. 392000. 235200. 252000. 156800. 190400.]
 [784000. 330400. 274400. 218400. 134400. 173600.]
 [884800. 436800. 296800. 280000. 184800. 229600.]
 [593600. 347200. 229600. 190400. 128800. 162400.]]


In [40]:
'''Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete()'''

import numpy as np
updated_sales_data = np.delete(sales_data, 1, axis=0)
updated_cost_data = np.delete(cost_data, 1, axis=0)
print("Updated Sales Data: ", updated_sales_data)
print("Updated Cost Data: ", updated_cost_data)

Updated Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Updated Cost Data:  [[640000 315000 220000 205000 125000 160000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [41]:
'''Question 74: Adding a New Store
A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array'''

import numpy as np
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
updated_sales_data = np.vstack((sales_data, delhi_sales))
updated_cost_data = np.vstack((cost_data, delhi_cost))
stores = np.append(stores, "Delhi")
print("Updated Sales Data: ", updated_sales_data)
print("Updated Cost Data: ", updated_cost_data)
print("Stores: ", stores)


Updated Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Updated Cost Data:  [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
Stores:  ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


In [42]:
'''Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack().'''

import numpy as np
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])
home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
updated_sales_data = np.column_stack((sales_data, home_appliance_sales))
updated_cost_data = np.column_stack((cost_data, home_appliance_cost))
print("Updated Sales Data: ", updated_sales_data)
print("Updated Cost Data: ", updated_cost_data)

Updated Sales Data:  [[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
Updated Cost Data:  [[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


In [43]:
'''Part 13: Sorting and Ranking
Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.'''
import numpy as np
total_sales = np.sum(sales_data, axis=1)
sorted_indices = np.argsort(total_sales)
sorted_stores = stores[sorted_indices]
sorted_sales = total_sales[sorted_indices]
print("Sorted Stores: ", sorted_stores)
print("Sorted Sales: ", sorted_sales)
print("Store Names and Sales Totals: ", list(zip(sorted_stores, sorted_sales)))

Sorted Stores:  ['Pune' 'Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
Sorted Sales:  [1980000 2270000 2295000 2310000 2820000]
Store Names and Sales Totals:  [(np.str_('Pune'), np.int64(1980000)), (np.str_('Bengaluru'), np.int64(2270000)), (np.str_('Hyderabad'), np.int64(2295000)), (np.str_('Chennai'), np.int64(2310000)), (np.str_('Mumbai'), np.int64(2820000))]


In [44]:
'''Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().'''

import numpy as np
profit = sales_data - cost_data
total_profit = np.sum(profit, axis=1)
sorted_indices = np.argsort(total_profit)[::-1]
ranked_stores = stores[sorted_indices]
ranked_profits = total_profit[sorted_indices]
print("Ranked Stores: ", ranked_stores)
print("Ranked Profits: ", ranked_profits)

Ranked Stores:  ['Mumbai' 'Hyderabad' 'Bengaluru' 'Chennai' 'Pune']
Ranked Profits:  [755000 610000 605000 600000 505000]


In [45]:
'''Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.'''
import numpy as np
total_revenue = np.sum(sales_data, axis=0)
sorted_indices = np.argsort(total_revenue)[::-1]
sorted_categories = categories[sorted_indices]
sorted_revenue = total_revenue[sorted_indices]
print("Sorted Categories: ", sorted_categories)
print("Sorted Revenue: ", sorted_revenue)

Sorted Categories:  ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Sports' 'Beauty']
Sorted Revenue:  [4290000 2185000 1600000 1415000 1175000 1010000]


In [46]:
'''Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name'''

import numpy as np
top_three_stores = np.sort(sales_data.flatten())[-3:]
top_three_indices = np.argsort(sales_data.flatten())[-3:]
top_three_stores_names = stores[top_three_indices // sales_data.shape[1]]
top_three_categories_names = categories[top_three_indices % sales_data.shape[1]]
print("Top Three Store-Category Sales: ", top_three_stores)
print("Top Three Store Names: ", top_three_stores_names)
print("Top Three Category Names: ", top_three_categories_names)

Top Three Store-Category Sales:  [ 850000  920000 1050000]
Top Three Store Names:  ['Bengaluru' 'Chennai' 'Mumbai']
Top Three Category Names:  ['Electronics' 'Electronics' 'Electronics']


In [49]:
'''Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.'''
import numpy as np
bottom_three_profits = np.sort(profit.flatten())[:3]
bottom_three_indices = np.argsort(profit.flatten())[:3]
bottom_three_stores_names = stores[bottom_three_indices // profit.shape[1]]
bottom_three_categories_names = categories[bottom_three_indices % profit.shape [1]]
print("Bottom Three Profits: ", bottom_three_profits)
print("Bottom Three Store Names: ", bottom_three_stores_names)
print("Bottom Three Category Names: ", bottom_three_categories_names)

Bottom Three Profits:  [55000 60000 60000]
Bottom Three Store Names:  ['Pune' 'Pune' 'Chennai']
Bottom Three Category Names:  ['Furniture' 'Sports' 'Sports']


In [48]:
'''Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile'''

import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
std_sales = np.std(sales_data)
var_sales = np.var(sales_data)
percentile_25 = np.percentile(sales_data, 25)
percentile_50 = np.percentile(sales_data, 50)
percentile_75 = np.percentile(sales_data, 75)
print("Minimum Sales: ", min_sales)
print("Maximum Sales: ", max_sales)
print("Mean Sales: ", mean_sales)
print("Median Sales: ", median_sales)
print("Standard Deviation of Sales: ", std_sales)
print("Variance of Sales: ", var_sales)
print("25th Percentile of Sales: ", percentile_25)
print("50th Percentile of Sales: ", percentile_50)
print("75th Percentile of Sales: ", percentile_75)

Minimum Sales:  175000
Maximum Sales:  1050000
Mean Sales:  389166.6666666667
Median Sales:  302500.0
Standard Deviation of Sales:  230322.53954448793
Variance of Sales:  53048472222.222206
25th Percentile of Sales:  228750.0
50th Percentile of Sales:  302500.0
75th Percentile of Sales:  416250.0


In [50]:
'''Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.'''
import numpy as np
std_deviation_stores = np.std(sales_data, axis=1)
most_varied_store_index = np.argmax(std_deviation_stores)
most_varied_store = stores[most_varied_store_index]
print("Standard Deviation of Stores: ", std_deviation_stores)
print("Most Varied Store: ", most_varied_store)
print("Store with the Most Variation: ", most_varied_store)

Standard Deviation of Stores:  [223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Most Varied Store:  Mumbai
Store with the Most Variation:  Mumbai


In [51]:
'''Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.'''
import numpy as np
std_deviation_categories = np.std(sales_data, axis=0)
most_varied_category_index = np.argmax(std_deviation_categories)
most_varied_category = categories[most_varied_category_index]
print("Standard Deviation of Categories: ", std_deviation_categories)
print("Most Varied Category: ", most_varied_category)



Standard Deviation of Categories:  [122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Most Varied Category:  Electronics


In [52]:
'''Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.'''
import numpy as np
company_wide_average_sales = np.mean(sales_data)
above_average_count = np.sum(sales_data > company_wide_average_sales)
print("Company-Wide Average Sales: ", company_wide_average_sales)
print("Above Average Count: ", above_average_count)

Company-Wide Average Sales:  389166.6666666667
Above Average Count:  10


In [53]:
'''Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.'''
import numpy as np
high_value_outliers = sales_data[sales_data > (np.mean(sales_data) + 1.5 * np.std(sales_data))]
print("High-Value Outliers: ", high_value_outliers)

High-Value Outliers:  [ 850000  780000  920000 1050000]


In [54]:
'''Part 15: Reshaping and Transformation
Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.'''
import numpy as np
flattened_sales_data = sales_data.flatten()
print("Flattened Sales Data: ", flattened_sales_data)


Flattened Sales Data:  [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [55]:
'''Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.
'''

import numpy as np
reshaped_sales_data_1 = sales_data.reshape(3, 10)
reshaped_sales_data_2 = sales_data.reshape(10, 3)
reshaped_sales_data_3 = sales_data.reshape(2, 15)
reshaped_sales_data_4 = sales_data.reshape(15, 2)
print("Reshaped Sales Data 1: ", reshaped_sales_data_1)
print("Reshaped Sales Data 2: ", reshaped_sales_data_2)
print("Reshaped Sales Data 3: ", reshaped_sales_data_3)
print("Reshaped Sales Data 4: ", reshaped_sales_data_4)

Reshaped Sales Data 1:  [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
Reshaped Sales Data 2:  [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
Reshaped Sales Data 3:  [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
Reshaped Sales Data 4:  [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  3

In [56]:
'''Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.'''
import numpy as np
transposed_sales_data = sales_data.T
print("Transposed Sales Data: ", transposed_sales_data)
print("Transposed Sales Data Shape: ", transposed_sales_data.shape)

Transposed Sales Data:  [[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
Transposed Sales Data Shape:  (6, 5)


In [57]:
'''Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.'''
import numpy as np
combined_sales_cost_data = np.vstack((sales_data, cost_data))
print("Combined Sales and Cost Data: ", combined_sales_cost_data)
print("Combined Sales and Cost Data Shape: ", combined_sales_cost_data.shape)


Combined Sales and Cost Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Combined Sales and Cost Data Shape:  (10, 6)


In [58]:
'''Question 90: Store-Level Combined Data
Create a three-dimensional array where:
First layer contains sales data
Second layer contains cost data
Use np.stack().
Display the shape of the new array.'''
import numpy as np
store_level_combined_data = np.stack((sales_data, cost_data), axis=0)
print("Store-Level Combined Data: ", store_level_combined_data)
print("Store-Level Combined Data Shape: ", store_level_combined_data.shape)

Store-Level Combined Data:  [[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Store-Level Combined Data Shape:  (2, 5, 6)


In [61]:
'''Part 16: Missing Data Scenario
The company discovers that some sales values were not recorded.

Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values'''
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

total_number_of_missing_values = np.sum(np.isnan(sales_with_missing))
location_of_missing_values = np.where(np.isnan(sales_with_missing))
stores_with_missing_values = np.unique(location_of_missing_values[0])
categories_with_missing_values = np.unique(location_of_missing_values[1])
print("Total Number of Missing Values: ", total_number_of_missing_values)
print("Location of Missing Values: ", list(zip(location_of_missing_values[0], location_of_missing_values[1])))
print("Stores with Missing Values: ", stores_with_missing_values)
print("Categories with Missing Values: ", categories_with_missing_values)

Total Number of Missing Values:  4
Location of Missing Values:  [(np.int64(0), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(4))]
Stores with Missing Values:  [0 1 3 4]
Categories with Missing Values:  [1 2 3 4]


In [62]:
'''Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.'''
import numpy as np
sales_with_missing[np.isnan(sales_with_missing)] = 0
print("Sales with Missing Values Replaced with Zero: ", sales_with_missing)

Sales with Missing Values Replaced with Zero:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [63]:
'''Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.
Use np.nanmean()'''
import numpy as np
average_sales = np.nanmean(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = average_sales
print("Sales with Missing Values Replaced with Company Average: ", sales_with_missing)


Sales with Missing Values Replaced with Company Average:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [64]:
'''Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.'''
import numpy as np
category_averages = np.nanmean(sales_with_missing, axis=0)
sales_with_missing[np.isnan(sales_with_missing)] = np.take(category_averages, np.where(np.isnan(sales_with_missing))[1])
print("Sales with Missing Values Replaced with Category Averages: ", sales_with_missing)



Sales with Missing Values Replaced with Category Averages:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [65]:
'''Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.'''
import numpy as np
total_sales_before = np.sum(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = 0
total_sales_after = np.sum(sales_with_missing)
print("Total Sales Before Replacing Missing Values with Zero: ", total_sales_before)
print("Total Sales After Replacing Missing Values with Zero: ", total_sales_after)
print("Total Sales Before Replacing Missing Values with Zero: ", total_sales_before)
print("Total Sales After Replacing Missing Values with Zero: ", total_sales_after)

Total Sales Before Replacing Missing Values with Zero:  10370000.0
Total Sales After Replacing Missing Values with Zero:  10370000.0
Total Sales Before Replacing Missing Values with Zero:  10370000.0
Total Sales After Replacing Missing Values with Zero:  10370000.0


In [35]:
'''Part 17: Conditional Business Decisions
Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().'''

import numpy as np
total_sales = np.nansum(sales_data, axis=1)
conditions = [
    total_sales > 2800000,
    (total_sales >= 2400000) & (total_sales <= 2800000),
    total_sales < 2400000,
]
choices = ["Excellent", "Good", "Needs Improvement"]
store_performance_labels = np.select(conditions, choices, default="Not Classified")
print("Store Performance Labels: ", store_performance_labels)

Store Performance Labels:  ['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


In [36]:
'''Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero'''
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
conditions = [
    profit > 200000,
    (profit >= 100000) & (profit <= 200000),
    profit < 100000,
    profit < 0,
]
choices = ["Highly Profitable", "Profitable", "Low Profit", "Loss"]
profitability_classification = np.select(conditions, choices, default="Not Classified")
print("Profitability Classification: ", profitability_classification)

Profitability Classification:  ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
 'Highly Profitable' 'Highly Profitable']


In [34]:
'''Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.'''
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
overall_profit_margin = np.mean(profit / total_sales)
conditions = [profit < 0,profit < 100000,profit <= 200000,profit > 200000]
choices = ["Loss", "Low Profit", "Profitable", "Highly Profitable"]
profitability_classification = np.select(conditions, choices, default="Not Classified")
print("Profitability Classification: ", profitability_classification)

Profitability Classification:  ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
 'Highly Profitable' 'Highly Profitable']


In [32]:
'''Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.'''
import numpy as np
average_sales = np.mean(sales_data, axis=0)
total_sales = np.sum(sales_data, axis=0)
total_cost = np.sum(cost_data, axis=0)
profit = total_sales - total_cost
profit_margin = profit / total_sales
conditions = [average_sales < 300000,profit_margin <= 0.25,profit_margin > 0.25,]
choices = ["Low Sales", "Low Profit Margin", "High Profit Margin"]
category_promotion_recommendation = np.select(conditions, choices, default="Not Recommended")
print("Category Promotion Recommendation: ", category_promotion_recommendation)

Category Promotion Recommendation:  ['Low Profit Margin' 'Low Profit Margin' 'High Profit Margin' 'Low Sales'
 'Low Sales' 'Low Sales']


In [31]:
'''Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.'''
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
profit_margin = profit / total_sales
conditions = [total_cost > 250000,profit_margin < 0.25,profit_margin >= 0.25,]
choices = ["High Cost", "Low Profit Margin", "High Profit Margin"]
cost_optimization_recommendation = np.select(conditions, choices, default="Not Recommended")
print("Cost Optimization Recommendation: ", cost_optimization_recommendation)

Cost Optimization Recommendation:  ['High Cost' 'High Cost' 'High Cost' 'High Cost' 'High Cost']


In [72]:
'''
Part 18: Inventory Scenario

Use the following inventory arrays:'''


import numpy as np
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

print(opening_stock)
print(units_sold)


[[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
[[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


In [73]:
'''Question 101: Closing Stock

Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold'''


import numpy as np
closing_stock = opening_stock - units_sold
print("Closing Stock: ", closing_stock)

Closing Stock:  [[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [74]:
'''Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.'''

import numpy as np
low_stock_indices = np.where(closing_stock < 30)
low_stock_stores = low_stock_indices[0]
low_stock_categories = low_stock_indices[1]
print("Low-Stock Stores: ", low_stock_stores)
print("Low-Stock Categories: ", low_stock_categories)

Low-Stock Stores:  [0 0 1 1 2 2 3 4 4]
Low-Stock Categories:  [0 3 0 3 0 3 0 0 3]


In [75]:
'''Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.'''
import numpy as np
unsold_stock_percentage = np.mean(opening_stock == 0) * 100
print("Percentage of Unsold Stock: ", unsold_stock_percentage)


Percentage of Unsold Stock:  0.0


In [76]:
'''Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.
Identify fast-moving store-category combinations.'''

import numpy as np
fast_moving_indices = np.where(np.sum(units_sold, axis=0) / np.sum(opening_stock, axis=0) > 0.8)
fast_moving_stores = fast_moving_indices[0]
fast_moving_categories = fast_moving_indices[0]
print("Fast-Moving Stores: ", fast_moving_stores)
print("Fast-Moving Categories: ", fast_moving_categories)

Fast-Moving Stores:  [1 2]
Fast-Moving Categories:  [1 2]


In [77]:
'''Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.'''

import numpy as np
total_units_sold = np.sum(units_sold, axis=0)
print("Total Units Sold: ", total_units_sold)

Total Units Sold:  [ 485 1950 1240  345  980  720]


In [78]:
'''Question 106: Store-Wise Units Sold
Calculate total units sold by each store.'''

import numpy as np
total_units_sold_by_store = np.sum(units_sold, axis=1)
print("Total Units Sold by Store: ", total_units_sold_by_store)



Total Units Sold by Store:  [1110 1175 1095 1390  950]


In [79]:
'''Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.'''
import numpy as np
best_store_index = np.argmax(total_units_sold_by_store)
print("Best Store by Unit Sales: ", best_store_index)

Best Store by Unit Sales:  3


In [80]:
'''Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.
Create a Boolean reorder matrix.'''
import numpy as np
reorder_required = closing_stock < 25
print("Boolean Reorder Required Matrix: ", reorder_required)

Boolean Reorder Required Matrix:  [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [81]:
'''Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.
Calculate reorder quantities only for combinations where closing stock is below 25.
For all other combinations, return zero.'''
import numpy as np
reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)
print("Reorder Quantity: ", reorder_quantity)

Reorder Quantity:  [[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


In [82]:
'''Part 19: Advanced NumPy Questions
Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().'''
import numpy as np
cumulative_category_sales = np.cumsum(sales_data, axis=1)
print("Cumulative Category Sales: ", cumulative_category_sales)

Cumulative Category Sales:  [[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [83]:
'''Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.'''
import numpy as np
flattened_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flattened_sales)
print("Cumulative Company Sales: ", cumulative_company_sales)

Cumulative Company Sales:  [  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [84]:
'''Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().'''
import numpy as np
sales_difference_between_categories = np.diff(sales_data, axis=1)
print("Sales Difference Between Categories: ", sales_difference_between_categories)

Sales Difference Between Categories:  [[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [86]:
'''Question 113: Unique Sales Values
Find all unique sales values in sales_data.
Also count the frequency of each value.'''
import numpy as np
unique_sales_values, value_counts = np.unique(sales_data, return_counts=True)
print("Unique Sales Values: ", unique_sales_values)
print("Value Counts: ", value_counts)


Unique Sales Values:  [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Value Counts:  [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [85]:
'''Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.
Return its location.'''


import numpy as np
value_to_search = 420000
location_of_value = np.where(sales_data == value_to_search)
print("Location of Value: ", location_of_value)

Location of Value:  (array([0]), array([1]))


In [89]:
'''Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.
Verify whether all combinations are profitable using np.all().'''
import numpy as np
sales_greater_than_cost = sales_data > cost_data
all_combinations_profitable = np.all(sales_greater_than_cost)
print("Sales Greater Than Cost: ", sales_greater_than_cost)
print("All Combinations Profitable: ", all_combinations_profitable)

Sales Greater Than Cost:  [[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All Combinations Profitable:  True


In [88]:
'''Question 116: Clip Profit Values
**For reporting purposes, management wants profit values limited to:
Minimum: ₹75,000 Maximum: ₹2,50,000 Use np.clip() to create a reporting profit array.**'''
import numpy as np
minimum_profit = 75000
maximum_profit = 250000
reporting_profit = np.clip(profit, minimum_profit, maximum_profit)
print("Reporting Profit: ", reporting_profit)


Reporting Profit:  [[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [87]:
'''Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:'''
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("Normalized Sales: ", normalized_sales)

Normalized Sales:  [[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [90]:
'''Question 118: Standardize Sales Data
Standardize sales using:
Standardized Sales = (Sales - Mean Sales) / Standard Deviation'''
import numpy as np
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print("Standardized Sales: ", standardized_sales)

Standardized Sales:  [[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [92]:
'''Question 119: Round Values
Convert profit margin values into:
Two decimal places Nearest whole number Floor values Ceiling values'''
import numpy as np
profit_margin = profit / sales_data
rounded_profit_margin = np.round(profit_margin, 2)
nearest_whole_number_profit_margin = np.round(profit_margin)
floor_values_profit_margin = np.floor(profit_margin)
ceiling_values_profit_margin = np.ceil(profit_margin)
print("Rounded Profit Margin: ", rounded_profit_margin)
print("Nearest Whole Number Profit Margin: ", nearest_whole_number_profit_margin)
print("Floor Values Profit Margin: ", floor_values_profit_margin)
print("Ceiling Values Profit Margin: ", ceiling_values_profit_margin)

Rounded Profit Margin:  [[0.25 0.25 0.29 0.25 0.34 0.29]
 [0.24 0.24 0.29 0.27 0.33 0.29]
 [0.24 0.24 0.28 0.25 0.35 0.28]
 [0.25 0.24 0.29 0.28 0.34 0.29]
 [0.23 0.23 0.27 0.24 0.34 0.29]]
Nearest Whole Number Profit Margin:  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Floor Values Profit Margin:  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Ceiling Values Profit Margin:  [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [69]:
'''Question 120: Save and Load Data
Save the following arrays as NumPy binary files:
sales_data.npy cost_data.npy profit_data.npy Load them back and verify that the loaded arrays are equal to the original arrays.'''
import numpy as np
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit)
loaded_sales_data = np.load("sales_data.npy")
loaded_cost_data = np.load("cost_data.npy")
loaded_profit_data = np.load("profit_data.npy")
print("Loaded Sales Data: ", loaded_sales_data)
print("Loaded Cost Data: ", loaded_cost_data)
print("Loaded Profit Data: ", loaded_profit_data)

Loaded Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Loaded Cost Data:  [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
Loaded Profit Data:  [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
